name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup default ${{ matrix.channel }}
      - name: Build
        run: cargo build --tests --workspace
      - name: Test
        run: cargo test --workspace
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta, nightly]
